### ISSUE TITLE
Citation/Reference

### ISSUE THREAD

**Issue by samuel-marsh** [hypercompetent/colorway#1]
Hi Lucas,

Love the package!!  I'd like to incorporate/adapt couple of the functions for use in visualization package I've been internally developing for our lab.  I'd like to reference the package/you in the documentation.  Other than citing the package URL is there anything else I should list in terms of `@authors`/ `@references` in documentation?

Thanks!
Sam

**Comment by hypercompetent** [comment]
Hi Sam,

I'm glad you like it. Feel free to adapt for your use. I've gone ahead and grabbed a DOI for citation or referencing here on Zenodo: https://zenodo.org/record/5167964#.YQ2Zr-hKguU .

Lucas Graybuck, & Samuel Marsh. (2021). hypercompetent/colorway: colorway v0.2.0 (v0.2.0). Zenodo. https://doi.org/10.5281/zenodo.5167964

Since you submitted a PR, I added you to DESCRIPTION as a contributor, and Zenodo grabbed you as an author in the citation text. Please let me know if you'd rather not be listed, and I'll see about an update.

Cheers,
-Lucas

**Comment by samuel-marsh** [comment]
Hey Lucas,

So sorry just realizing I never responded here.  Thanks so much!  I have no issues with it as long as good by you.  Thanks again!

Sam
